FROM node:14.17.0-slim

ENV NODE_ENV=production
WORKDIR /app

COPY package.json .
COPY package-lock.json .
RUN npm install --production

COPY public ./public/
COPY src ./src/
RUN npm run build
CMD ["npm", "start"]
